#!/bin/bash

export PATH=/home/xqx/data/xqx/projects/llvm-test/buildllvm31/Release+Debug+Asserts/bin:$PATH
DIR=$(dirname "${BASH_SOURCE[0]}")
OPT="`llvm-config --bindir`/opt"
exec ${OPT} -disable-output -load=${DIR}/../lib/libintck.so \
	-O2 \
	-int-sat $@ 2>&1

#	-xqx-cg \
	#-xCallPaths \
